### ISSUE TITLE
New iready hack

### ISSUE THREAD

**Issue by Spideyboyjk2** [playstation452/All-Hacks#15]
Nullify doesn't work and I don't have a hack rn pls helppppp

**Comment by playstation452** [comment]
i can try

**Comment by playstation452** [comment]
ok try the new one

**Comment by Spideyboyjk2** [comment]
Thanks

**Comment by Spideyboyjk2** [comment]
Lemme check later cuase I got some stuff to do

**Comment by Spideyboyjk2** [comment]
Just check and sadly it doesn't work.

We need one that was newly made so iready has surely not blocked it

**Comment by playstation452** [comment]
ok
