### ISSUE TITLE
you didnt make this code

### ISSUE THREAD

**Issue by C0mputa** [playstation452/All-Hacks#19]
most of this code is stolen from other github things i dont know if there a reupload but people asking for him to fix he probably cant since its not his code

**Comment by playstation452** [comment]
i cant code? 
https://github.com/wdnc-mc-client/WDNC-Client
https://github.com/wdnc-mc-client/WDNC-kitbot
https://github.com/stars/playstation452/lists/geometry-dash


keep crying nigga

**Comment by C0mputa** [comment]
> i cant code? https://github.com/wdnc-mc-client/WDNC-Client https://github.com/wdnc-mc-client/WDNC-kitbot https://github.com/stars/playstation452/lists/geometry-dash
> 
> keep crying nigga

touche
