### ISSUE TITLE
What hacks should i add

### ISSUE THREAD

**Issue by playstation452** [playstation452/All-Hacks#2]
Put all of your ideas here

**Comment by playstation452** [comment]
ok i did my school block edpuzzles so i just used the read.md of the github you sent me

**Comment by FazePablo2** [comment]
Pls?

**Comment by FazePablo2** [comment]
And if you can't thats fine don't want to waste your time.

**Comment by playstation452** [comment]
ok i will

**Comment by lukey2323** [comment]
hacks for quizzes? like a flooder

**Comment by playstation452** [comment]
> hacks for quizzes? like a flooder

yes

**Comment by liamsusyeh** [comment]
quizzes

**Comment by maskedwrrg** [comment]
fix i-ready hacks

**Comment by LogiAnimations** [comment]
Quizlet hacks please

**Comment by uwugirl2020** [comment]
iready\
pls

**Comment by nonecaresand211** [comment]
add some new hacks that actually work for gimkit. Add some more hacks for kahoot too

**Comment by playstation452** [comment]
> quizizz

it works

**Comment by playstation452** [comment]
> add some new hacks that actually work for gimkit. Add some more hacks for kahoot too

all the others need tamper monkey

**Comment by playstation452** [comment]
if you want to add stuff send a pull request

**Comment by uwugirl2020** [comment]
i ready hack pls preety pls🥺🥺

**Comment by playstation452** [comment]
> i ready hack pls preety pls🥺🥺
the i ready hack alr works

**Comment by uwugirl2020** [comment]
can i have the link then pls 
it is 
javascript:????????

**Comment by uwugirl2020** [comment]
pls

**Comment by uwugirl2020** [comment]
help

**Comment by uwugirl2020** [comment]
give me link

**Comment by playstation452** [comment]
> give me link

https://github.com/playstation452/All-Hacks/tree/main/I-Ready%20Hacks

**Comment by uwugirl2020** [comment]
add iready that works pls
and a \

**Comment by uwugirl2020** [comment]
![Uploading ffail 7.png…]()

**Comment by uwugirl2020** [comment]
![ffail 7](https://user-images.githubusercontent.com/128755724/232796533-cccebdf3-a5ef-4320-a628-473e3369cd52.png)

**Comment by chocodagoat** [comment]
add gimkit hacks for capture the flag and if you can add my discord its ChocoIsCalling#4172 if your done with the script and instructions on how i can use

**Comment by uwugirl2020** [comment]
i know but it wont work

**Comment by playstation452** [comment]
> i know but it wont work

then its prob blocked by group policy

**Comment by uwugirl2020** [comment]
thanks
any ody know a hack to ixl

**Comment by xXxKingNoodlesxXx** [comment]
Could you get IXL and Seterra hacks?
pls

**Comment by xXxKingNoodlesxXx** [comment]
Also the instructions to get them and use them

**Comment by playstation452** [comment]
> ixl hack pls

theres no way

**Comment by maskedwrrg** [comment]
I have found new i-ready hack

**Comment by maskedwrrg** [comment]
https://github.com/RipAngelhacks/i-skip/blob/main/Nullify%20bookmark

**Comment by uwugirl2020** [comment]
dose it start with javascript

**Comment by uwugirl2020** [comment]
thank you so much

**Comment by playstation452** [comment]
new one

**Comment by Someone1201alt** [comment]
Mathia or schoology?
