### ISSUE TITLE
tower defense get tokens broken

### ISSUE THREAD

**Issue by test21321332133123** [playstation452/All-Hacks#25]
it gives me the tokens, but after i click done, it just starts restarting the bookmarklet over and over again, could you please fix this as it is my favorite blooket game :thumbs-up:

**Comment by playstation452** [comment]
if its your favorite blooket game then why hack on it lol

**Comment by Unknown69696969696969** [comment]
i guess makes it funner????

**Comment by DES362** [comment]
Yes

**Comment by playstation452** [comment]
its because i have not updated it

**Comment by playstation452** [comment]
close this issue when you read it

**Comment by test21321332133123** [comment]
the point of submitting an issue is for the person who made the bookmarklet to fix it. if u dont know that then idek how dumb u are
