### ISSUE TITLE
I have a request

### ISSUE THREAD

**Issue by Unknown69696969696969** [playstation452/All-Hacks#28]
Can you help me with something pls reply soon would be really appreciated

**Comment by playstation452** [comment]
what

**Comment by Unknown69696969696969** [comment]
i forgot

**Comment by Unknown69696969696969** [comment]
oh now i remeber could you help me with coding i want to do hacks too but im too lost in the process and where to put the code. I have the code but i don't know where to put it pls help me. You don't have to just asking.
